apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-nginx
  namespace: demo-argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-nginx
  template:
    metadata:
      labels:
        app: demo-nginx
    spec:
      containers:
      - name: nginx
        image: nginxinc/nginx-unprivileged:1.25
        ports:
        - containerPort: 80
